--------------------------------------------------------
--  File created - Wednesday-February-17-2021   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Sequence ANSWER_ID_GENERATOR
--------------------------------------------------------

       CREATE SEQUENCE  "ADMIN"."ANSWER_ID_GENERATOR"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 130 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;
    --------------------------------------------------------
    --  DDL for Sequence HIBERNATE_SEQUENCE
    --------------------------------------------------------
    
       CREATE SEQUENCE  "ADMIN"."HIBERNATE_SEQUENCE"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 21 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;
    --------------------------------------------------------
    --  DDL for Sequence PERMISSION_ID_GENERATOR
    --------------------------------------------------------
    
       CREATE SEQUENCE  "ADMIN"."PERMISSION_ID_GENERATOR"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 69 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;
    --------------------------------------------------------
    --  DDL for Sequence PROGRESS_ID_GENERATOR
    --------------------------------------------------------
    
       CREATE SEQUENCE  "ADMIN"."PROGRESS_ID_GENERATOR"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 88 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;
    --------------------------------------------------------
    --  DDL for Sequence QUESTION_ID_GENERATOR
    --------------------------------------------------------
    
       CREATE SEQUENCE  "ADMIN"."QUESTION_ID_GENERATOR"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 128 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;
    --------------------------------------------------------
    --  DDL for Sequence QUIZ_ID_GENERATOR
    --------------------------------------------------------
    
       CREATE SEQUENCE  "ADMIN"."QUIZ_ID_GENERATOR"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 137 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;
    --------------------------------------------------------
    --  DDL for Sequence USER_ID_GENERATOR
    --------------------------------------------------------
    
       CREATE SEQUENCE  "ADMIN"."USER_ID_GENERATOR"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 190 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;
--------------------------------------------------------
--  DDL for Table ANSWERS
--------------------------------------------------------

  CREATE TABLE "ADMIN"."ANSWERS" 
   (	"ANSWERID" NUMBER, 
	"ANSWERTEXT" VARCHAR2(255 BYTE), 
	"QUESTIONID" NUMBER, 
	"ISCORRECT" NUMBER, 
	"ORDERING" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table PERMISSIONS
--------------------------------------------------------

  CREATE TABLE "ADMIN"."PERMISSIONS" 
   (	"PERMISSIONID" NUMBER, 
	"USERID" NUMBER, 
	"QUIZID" NUMBER, 
	"RELATIONSHIP" VARCHAR2(255 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table PROGRESS
--------------------------------------------------------

  CREATE TABLE "ADMIN"."PROGRESS" 
   (	"PROGRESSID" NUMBER, 
	"USERID" NUMBER, 
	"ANSWERID" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table QUESTIONS
--------------------------------------------------------

  CREATE TABLE "ADMIN"."QUESTIONS" 
   (	"QUESTIONID" NUMBER, 
	"QUIZID" NUMBER, 
	"QUESTIONTYPE" VARCHAR2(255 BYTE), 
	"DESCRIPTION" VARCHAR2(255 BYTE), 
	"ORDERING" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table QUIZZES
--------------------------------------------------------

  CREATE TABLE "ADMIN"."QUIZZES" 
   (	"QUIZID" NUMBER, 
	"USERID" NUMBER, 
	"NAME" VARCHAR2(255 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table USERS
--------------------------------------------------------

  CREATE TABLE "ADMIN"."USERS" 
   (	"USERID" NUMBER, 
	"USERNAME" VARCHAR2(255 BYTE), 
	"PASSWORDHASH" VARCHAR2(255 BYTE), 
	"TEACHER" NUMBER, 
	"ROLE" VARCHAR2(255 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
REM INSERTING into ADMIN.ANSWERS
SET DEFINE OFF;
Insert into ADMIN.ANSWERS (ANSWERID,ANSWERTEXT,QUESTIONID,ISCORRECT,ORDERING) values (1,'19',21,1,1);
REM INSERTING into ADMIN.PERMISSIONS
SET DEFINE OFF;
REM INSERTING into ADMIN.PROGRESS
SET DEFINE OFF;
Insert into ADMIN.PROGRESS (PROGRESSID,USERID,ANSWERID) values (1000,9,1);
Insert into ADMIN.PROGRESS (PROGRESSID,USERID,ANSWERID) values (23,4,1);
REM INSERTING into ADMIN.QUESTIONS
SET DEFINE OFF;
Insert into ADMIN.QUESTIONS (QUESTIONID,QUIZID,QUESTIONTYPE,DESCRIPTION,ORDERING) values (21,4,'Multiple Choice','What is 9 + 10?',1);
REM INSERTING into ADMIN.QUIZZES
SET DEFINE OFF;
Insert into ADMIN.QUIZZES (QUIZID,USERID,NAME) values (4,4,'Testing Quiz');
Insert into ADMIN.QUIZZES (QUIZID,USERID,NAME) values (70,8,'Imagine imagining');
Insert into ADMIN.QUIZZES (QUIZID,USERID,NAME) values (64,8,'Imagine imagining');
Insert into ADMIN.QUIZZES (QUIZID,USERID,NAME) values (68,8,'Sample Quiz');
REM INSERTING into ADMIN.USERS
SET DEFINE OFF;
Insert into ADMIN.USERS (USERID,USERNAME,PASSWORDHASH,TEACHER,ROLE) values (4,'alice','/N4rLtula/QIYB+3If6bXDONEO5CnqBPrlURto+/j7k=',null,'ADMIN');
Insert into ADMIN.USERS (USERID,USERNAME,PASSWORDHASH,TEACHER,ROLE) values (111,'Asuna','nGmgtytELMrD5qqqdjDRLys1H+OV6f5mfvoJB83pDaU=',10,'STUDENT');
Insert into ADMIN.USERS (USERID,USERNAME,PASSWORDHASH,TEACHER,ROLE) values (151,'anotherTest','/N4rLtula/QIYB+3If6bXDONEO5CnqBPrlURto+/j7k=',8,'STUDENT');
Insert into ADMIN.USERS (USERID,USERNAME,PASSWORDHASH,TEACHER,ROLE) values (9,'Bob','/N4rLtula/QIYB+3If6bXDONEO5CnqBPrlURto+/j7k=',8,'STUDENT');
Insert into ADMIN.USERS (USERID,USERNAME,PASSWORDHASH,TEACHER,ROLE) values (8,'Test','/N4rLtula/QIYB+3If6bXDONEO5CnqBPrlURto+/j7k=',null,'TEACHER');
Insert into ADMIN.USERS (USERID,USERNAME,PASSWORDHASH,TEACHER,ROLE) values (69,'AYAYA Clap','7NcYcNGWMxapfjrDQIyYNa2M8PPBvHA1J8MCZVNPda4=',8,'STUDENT');
Insert into ADMIN.USERS (USERID,USERNAME,PASSWORDHASH,TEACHER,ROLE) values (10,'charlie','/N4rLtula/QIYB+3If6bXDONEO5CnqBPrlURto+/j7k=',null,'TEACHER');
Insert into ADMIN.USERS (USERID,USERNAME,PASSWORDHASH,TEACHER,ROLE) values (131,'john','/N4rLtula/QIYB+3If6bXDONEO5CnqBPrlURto+/j7k=',8,'STUDENT');
Insert into ADMIN.USERS (USERID,USERNAME,PASSWORDHASH,TEACHER,ROLE) values (150,'Bar','/N4rLtula/QIYB+3If6bXDONEO5CnqBPrlURto+/j7k=',10,'STUDENT');
--------------------------------------------------------
--  Constraints for Table PERMISSIONS
--------------------------------------------------------

  ALTER TABLE "ADMIN"."PERMISSIONS" ADD PRIMARY KEY ("PERMISSIONID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table QUESTIONS
--------------------------------------------------------

  ALTER TABLE "ADMIN"."QUESTIONS" ADD PRIMARY KEY ("QUESTIONID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table USERS
--------------------------------------------------------

  ALTER TABLE "ADMIN"."USERS" ADD PRIMARY KEY ("USERID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "ADMIN"."USERS" ADD UNIQUE ("USERNAME")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table ANSWERS
--------------------------------------------------------

  ALTER TABLE "ADMIN"."ANSWERS" ADD PRIMARY KEY ("ANSWERID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table QUIZZES
--------------------------------------------------------

  ALTER TABLE "ADMIN"."QUIZZES" ADD PRIMARY KEY ("QUIZID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table PROGRESS
--------------------------------------------------------

  ALTER TABLE "ADMIN"."PROGRESS" ADD PRIMARY KEY ("PROGRESSID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table ANSWERS
--------------------------------------------------------

  ALTER TABLE "ADMIN"."ANSWERS" ADD FOREIGN KEY ("QUESTIONID")
	  REFERENCES "ADMIN"."QUESTIONS" ("QUESTIONID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table PERMISSIONS
--------------------------------------------------------

  ALTER TABLE "ADMIN"."PERMISSIONS" ADD CONSTRAINT "FK_PERMISSION_USER" FOREIGN KEY ("USERID")
	  REFERENCES "ADMIN"."USERS" ("USERID") ENABLE;
  ALTER TABLE "ADMIN"."PERMISSIONS" ADD FOREIGN KEY ("QUIZID")
	  REFERENCES "ADMIN"."QUIZZES" ("QUIZID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table PROGRESS
--------------------------------------------------------

  ALTER TABLE "ADMIN"."PROGRESS" ADD FOREIGN KEY ("ANSWERID")
	  REFERENCES "ADMIN"."ANSWERS" ("ANSWERID") ENABLE;
  ALTER TABLE "ADMIN"."PROGRESS" ADD CONSTRAINT "FK_PROGRESS_USER" FOREIGN KEY ("USERID")
	  REFERENCES "ADMIN"."USERS" ("USERID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table QUESTIONS
--------------------------------------------------------

  ALTER TABLE "ADMIN"."QUESTIONS" ADD FOREIGN KEY ("QUIZID")
	  REFERENCES "ADMIN"."QUIZZES" ("QUIZID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table QUIZZES
--------------------------------------------------------

  ALTER TABLE "ADMIN"."QUIZZES" ADD CONSTRAINT "FK_QUIZ_USER" FOREIGN KEY ("USERID")
	  REFERENCES "ADMIN"."USERS" ("USERID") ENABLE;
